rendezvous_server = 'rs-ny.rustdesk.com:21116'
nat_type = 2
serial = 0
unlock_pin = ''
trusted_devices = ''

[options]
av1-test = 'N'
direct-server = 'Y'
approve-mode = 'click'
allow-only-conn-window-open = 'Y'
local-ip-addr = ''
